"""add webhook url event unique constraint

Revision ID: 127b0dde3b19
Revises: 82f050d35322
Create Date: 2026-10-08 18:14:39.338909

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '127b0dde3b19'
down_revision: Union[str, Sequence[str], None] = '82f050d35322'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('webhooks', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_webhook_url_event', ['url', 'event'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('webhooks', schema=None) as batch_op:
        batch_op.drop_constraint('unique_webhook_url_event', type_='unique')

    # ### end Alembic commands ###
